// <auto-generated />
namespace JobOffers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ApplayForJobs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ApplayForJobs));
        
        string IMigrationMetadata.Id
        {
            get { return "202108110156050_ApplayForJobs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
